Repository TiimMate/TeamMateServer, pull requests merged in 2024-02, with the labels that each got.

#114 [REFACTOR] 종목별 나의 팀 조회 API 응답 수정
  src/daos/team.dao.ts
Labels: ♻️ refactor

#115 [FEAT] 리뷰 작성 가능한 기한 설정
  src/services/reviews.service.ts
Labels: ✨ feature

#130 [FEAT] 게스트 마감 필드 추가
  src/config/response.status.ts
  src/constants/guest-status.constant.ts
  src/controllers/matchings.controller.ts
  src/daos/guest-user.dao.ts
  src/daos/guest.dao.ts
  src/dtos/guests.dto.ts
  src/dtos/matchings.dto.ts
  src/models/guest-user.model.ts
  src/models/guest.model.ts
  src/services/guests.service.ts
  src/services/matchings.service.ts
Labels: ✨ feature

#129 [REFACTOR] 게스트 목록 조회 API 페이징 추가
  src/daos/guest.dao.ts
  src/dtos/guests.dto.ts
  src/models/guest.model.ts
  src/schemas/fields.ts
  src/services/guests.service.ts
Labels: ♻️ refactor

#134 [REFACTOR] 레벨 범위 변경으로 인한 필터링 수정
  src/constants/level.constant.ts
  src/daos/game.dao.ts
  src/daos/guest.dao.ts
  src/daos/profile.dao.ts
  src/daos/team.dao.ts
  src/dtos/games.dto.ts
  src/dtos/guests.dto.ts
  src/dtos/matchings.dto.ts
  src/dtos/users.dto.ts
  src/schemas/fields.ts
Labels: ♻️ refactor

#137 [FEAT] 게스트 API 게임 소요시간 필드 추가
  src/daos/guest.dao.ts
  src/dtos/guests.dto.ts
  src/dtos/matchings.dto.ts
  src/models/guest.model.ts
  src/schemas/fields.ts
  src/schemas/guest.schema.ts
Labels: ✨ feature

#138 [FEAT] 종목별 선수 정보 수정 및 조회 API에 프로필 사진 포함
  src/daos/user.dao.ts
  src/dtos/users.dto.ts
  src/models/user.model.ts
  src/schemas/fields.ts
  src/schemas/user-profile.schema.ts
Labels: ✨ feature

#149 [REFACTOR] 종목별 선수 정보 조회 API 응답 수정
  src/daos/user.dao.ts
  src/dtos/users.dto.ts
Labels: ♻️ refactor

#151 [REFACTOR] 종목별 선수 정보 조회 API 엔드포인트 수정
  src/controllers/users.controller.ts
  src/routes/users.route.ts
  src/services/users.service.ts
Labels: ♻️ refactor

#153 [BUGFIX] 종목별 선수 정보 조회 API 엔드포인트 오타 수정
  src/routes/users.route.ts
Labels: 🐛 bug

#156 [FEAT] 게스트 조회 데이터 추가
  src/daos/guest.dao.ts
  src/dtos/guests.dto.ts
Labels: ✨ feature

#164 [FEAT] 게스트 상세 조회, 호스팅 신청자 조회 응답에 프로필 추가
  src/daos/guest-user.dao.ts
  src/dtos/guests.dto.ts
  src/dtos/matchings.dto.ts
Labels: ✨ feature

#167 [CI] Github Actions 동작 테스트
  .github/workflows/dev_deploy.yml
Labels: 👷🏻 ci

#168 [CI] Github Actions 동작 테스트
  .github/workflows/dev_deploy.yml
Labels: 👷🏻 ci

#169 [CI] Github Actions 동작 테스트
  package.json
Labels: 👷🏻 ci

#170 [CI] Github Actions 동작 테스트
  .platform/nignx/nginx.conf
  Procfile
  package-lock.json
  package.json
  src/app.ts
  src/controllers/health.controller.ts
  src/routes/health.route.ts
  webpack.config.js
Labels: 👷🏻 ci

#172 [CI] Github Actions 동작 테스트
  package-lock.json
  package.json
  webpack.config.js
Labels: 👷🏻 ci

#174 [CI] CI/CD 파이프라인 구축
  .github/workflows/dev_deploy.yml
Labels: 👷🏻 ci

#175 [CI] 502 Bad Gateway 원인 찾기
  src/app.ts
Labels: 👷🏻 ci

#179 [BUGFIX] build 시 데이터베이스 에러 문제 해결
  src/app.ts
  src/config/config.ts
  src/models/index.ts
Labels: 🐛 bug, 👷🏻 ci

#180 [CI] CI/CD 파이프라인 구축
  src/app.ts
Labels: 👷🏻 ci

#181 [CI] 배포 실패 원인 찾기
  src/app.ts
Labels: 🐛 bug, 👷🏻 ci

#187 [CI] 배포 테스트
  src/app.ts
Labels: 👷🏻 ci

#188 [CI] 배포 테스트를 위해 수정했던 사항들 되돌리기
  src/app.ts
  webpack.config.js
Labels: 👷🏻 ci

#190 [FEAT] 내가 쓴 대관정보 글 조회 API 구현 및 내가 쓴 글 조회 API 수정
  src/controllers/posts.controller.ts
  src/daos/post.dao.ts
  src/routes/posts.route.ts
  src/services/posts.service.ts
Labels: ✨ feature

#197 [FEAT] 매칭내역 조회 리뷰 여부 추가
  src/controllers/matchings.controller.ts
  src/daos/game.dao.ts
  src/daos/guest-user.dao.ts
  src/dtos/matchings.dto.ts
  src/routes/matchings.route.ts
  src/services/matchings.service.ts
Labels: ✨ feature

#196 [FEAT] 리뷰에 따른 실력 및 매너 레벨 부여와 업데이트 기능 도입
  src/daos/team-review.dao.ts
  src/daos/team.dao.ts
  src/daos/user-review.dao.ts
  src/daos/user.dao.ts
  src/services/reviews.service.ts
Labels: ✨ feature

#192 [BUGFIX] 새로운 팀 생성 및 팀 수정 API에서 MX 입력 시 500 에러
  src/models/team.model.ts
Labels: 🐛 bug

#189 [REFACTOR] 팀 초대 코드 길이 수정
  src/services/teams.service.ts
Labels: ♻️ refactor
